[package]
name = "json_to_bson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.7.0"
serde = "1.0.190"
serde_bencode = "0.2.4"
serde_json = "1.0.107"
zstd = "0.13.0"
